# Generated by Django 3.2.8 on 2022-11-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterLearner', '0004_auto_20221112_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerparent',
            name='Parenting_type',
            field=models.CharField(blank=True, choices=[('OTHER', 'OTHER'), ('FATHER', 'Father'), ('MOTHER', 'Mother')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registerstudent',
            name='Student_Gender',
            field=models.CharField(blank=True, choices=[('FEMALE', 'Female'), ('MALE', 'Male')], max_length=10, null=True, verbose_name='Students Gender'),
        ),
        migrations.AlterField(
            model_name='registerstudent',
            name='Student_Grade',
            field=models.CharField(blank=True, choices=[('Grade_8', 'Grade 8'), ('Grade_9', 'Grade 9'), ('Grade_10', 'Grade 10'), ('Grade_11', 'Grade 11'), ('Grade_12', 'Grade 12')], max_length=50, null=True, verbose_name='Registered Grade'),
        ),
        migrations.AlterField(
            model_name='registerstudent',
            name='Student_subject',
            field=models.CharField(blank=True, choices=[('Engineering', 'Engineering'), ('Commence', 'Commence'), ('Sports', 'Sports')], max_length=50, null=True, verbose_name='Select main Subject'),
        ),
    ]
