# Generated by Django 3.2.8 on 2022-11-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterLearner', '0007_auto_20221113_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerparent',
            name='Parenting_type',
            field=models.CharField(blank=True, choices=[('FATHER', 'Father'), ('OTHER', 'OTHER'), ('MOTHER', 'Mother')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registerstudent',
            name='Student_Grade',
            field=models.CharField(blank=True, choices=[('Grade_8', 'Grade_8'), ('Grade_9', 'Grade_9'), ('Grade_10', 'Grade_10'), ('Grade_11', 'Grade_11'), ('Grade_12', 'Grade_12')], max_length=50, null=True, verbose_name='Registered Grade'),
        ),
    ]
