# Generated by Django 3.2.8 on 2022-11-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterLearner', '0009_alter_registerparent_parenting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerparent',
            name='Parenting_type',
            field=models.CharField(blank=True, choices=[('MOTHER', 'Mother'), ('OTHER', 'OTHER'), ('FATHER', 'Father')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registerstudent',
            name='Student_Grade',
            field=models.CharField(blank=True, choices=[('Grade_8', 'Grade 8'), ('Grade_9', 'Grade 9'), ('Grade_10', 'Grade 10'), ('Grade_11', 'Grade 11'), ('Grade_12', 'Grade 12')], max_length=50, null=True, verbose_name='Registered Grade'),
        ),
    ]
