# Generated by Django 3.2.8 on 2022-11-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterLearner', '0010_auto_20221113_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerparent',
            name='Parenting_type',
            field=models.CharField(blank=True, choices=[('MOTHER', 'Mother'), ('FATHER', 'Father'), ('OTHER', 'OTHER')], max_length=50, null=True),
        ),
    ]
